version: '3.6'
services:
  rails:
    build:
      context: .
      dockerfile: "Dockerfile"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ".:/app"
      - "bundle:/usr/local/bundle"
      - "node_modules:/app/node_modules"
    ports:
      - "4000:3000"
    tty: true
    stdin_open: true
volumes:
  bundle:
  node_modules:
