version: '3.6'
services:
  rails:
    build:
      context: .
      dockerfile: "Dockerfile"
    environment:
      - "DATABASE_USERNAME=root"
      - "DATABASE_PASSWORD=password"
      - "DATABASE_HOST=db"
      - "DATABASE_PORT=3306"
      - "REDIS_URL_DEVELOPMENT=redis://redis:6379/0"
      - "REDIS_URL_TEST=redis://redis:6379/1"
    command: bash -c "bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ".:/app"
      - "bundle:/usr/local/bundle"
      - "node_modules:/app/node_modules"
    ports:
      - "4000:3000"
    tty: true
    stdin_open: true
    depends_on:
      - db
      - redis
  db:
    image: "mysql:5.7"
    environment:
      - "MYSQL_ROOT_PASSWORD=password"
    volumes:
      - "db-data:/var/lib/mysql"
    ports:
      - "4306:3306"
  redis:
    image: "redis:5.0.7"
    ports:
      - "7379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
volumes:
  bundle:
  node_modules:
  db-data:
  redis-data:
